//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int ClientId { get; set; }
        public string Description { get; set; }
        public string ClientName { get; set; }
        public string Project { get; set; }
        public string ClientEmail { get; set; }
        public int Rate { get; set; }
        public bool TermsAndService { get; set; }
        public Nullable<bool> special { get; set; }
    }
}
