//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDetail
    {
        public int ProjectId { get; set; }
        public string ProjectType { get; set; }
        public string Description { get; set; }
        public string DeveloperName { get; set; }
        public string DeveloperEmail { get; set; }
    }
}
