//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SchoolManagementEntities : DbContext
    {
        public SchoolManagementEntities()
            : base("name=SchoolManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Student> Students { get; set; }
    
        [DbFunction("SchoolManagementEntities", "StudentDataStore")]
        public virtual IQueryable<Student> StudentDataStore()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Student>("[SchoolManagementEntities].[StudentDataStore]()");
        }

        public System.Data.Entity.DbSet<SchoolManagement.Models.StudentDataStore_Result> StudentDataStore_Result { get; set; }
    }
}
